//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectoryOfEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DirectoryOfEmployee()
        {
            this.ReportCards = new HashSet<ReportCard>();
        }
    
        public int ServiceNumber { get; set; }
        public string Surname { get; set; }
        public int Discharge { get; set; }
        public int Factory { get; set; }
    
        public virtual ListOfFactory ListOfFactory { get; set; }
        public virtual TariffReference TariffReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCard> ReportCards { get; set; }
    }
}
